title = "november has come"
date = 2017-11-19
tags = ["etc"]
content = """
<p>Wow. I can’t believe it’s been two years since my last blog post.
    I’ve learned a lot since the start of this blog. Well, here I am.
    I read a bunch of books on programming. I got my diploma and started working on a degree.
    Man, how time flies.</p>

<p>I’m trying to be more conscious of the world around me.
    I’m using Linux whenever possible, but some classes <em>require</em> otherwise.
    Luckily spinning up a VM is never too hard.
    I’ve tested out every desktop environment under the sea before finally settling on Gnome.
    I still can’t find a suitable terminal or file manager.
    These are two things that macOS seem to get right, but which no-one else can.</p>

<p>Ligatures! I love them. The mozilla foundation is a developer’s best friend.
    FiraMono/FiraCode. Rust. Firefox nightly. Just&hellip; Everything.
    They’re so great right now! I’m glad all their efforts are catching up to them :)</p>

<p>I’ve also learned a bit of OpenGL.
    I bought a domain and made <a href="http://ajitvpai.com" rel="external">a website</a>
    which blew up on reddit for a minute. I started learning Rust and Kotlin.</p>

<p>The Pokemon project is still ongoing!
    It’s currently in a private github repository,
    and I think I’ll release it when the code is pretty enough.
    I’m refactoring the old code, updating it with new knowledge,
    and replacing Java with Kotlin as I go.
    Planning for battles - the largest part of development - is nearly complete.
    Everything else should move along pretty quickly,
    and progress should <em>look</em> much faster when that happens.</p>

<p>I’m sure I’m forgetting some things, but this will do for now.</p>
"""

