[package]
name = "dwbrite-com"
version = "0.1.0"
authors = ["Devin Brite <devin@dwbrite.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"