apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.web_server.service.name }}
  labels:
    {{- include "dwbrite-com.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.web_server.service.port }}
      targetPort: {{ .Values.web_server.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "dwbrite-com.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-main

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.media_server.service.name }}
  labels:
    {{- include "dwbrite-com.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.media_server.service.port }}
      targetPort: {{ .Values.media_server.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "dwbrite-com.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-media
