title = "pocket progress 3"
date = 2015-07-06
tags = ["pkmn"]
content = """
<noscript class="media-noscript">
    <img src="/blog/media/pocket-progress/collision-and-animation2.gif" alt="image"/>
</noscript>

<p>Look at how far we’ve come! It’s not really that much but it’s exciting to me.
    Here you can see animations for running, biking, and cliff jumping in action!
    Cliff jumping still needs the offset for the sprite, the shadow,
    and the dust particles when you land, but the movement and animation frames are all in place!</p>

<p>This gif is a bit lower quality than the last one, even though it’s still at 15FPS,
    but it gets the point across. Anyway, that’s it for now. </p>

<p><s>Make sure to follow if you’re interested in this project.
        If you want to know what’s being done every day follow my
        <a href="http://dwbriteupdates.tumblr.com/" rel="noreferrer noopener">daily updates</a> page.</s></p>

<p>It isn’t shown in the gif, but you can no longer phase through the cliffs going upwards.</p>
"""
