title = "pocket progress 2"
date = 2015-06-27
tags = ["pkmn"]
content = """
<m src="collision-and-animation.gif" >

<p>Collision and animations are looking good right now.
    Here’s a gif of where I’m at.
    It took me all day to figure out what the hell I was doing wrong with interrupting walking into walls. </p>

<p>Anyway, I also overhauled the movement and controls I’d put in yesterday
    because I realized exactly how the real games handled it.</p>

<p>You can see travelling through areas right in this, which is nice,
    and you can also see that I haven’t programmed in collision for cliffs yet. :x</p>

<p>I had to keep the gif at 15FPS to make sure it was under 2MB while not looking being mangled by compression,
    but the game does in fact run at 60FPS, just like a real Gameboy game.</p>

<p>That’s pretty much it for now.
    Make sure to check the Live Updates page on my blog for live updates of what I’ve done or am doing. Bye!</p>
"""
