title = "retrospective on rust"
date = 2021-01-14
tags = ["etc"]
hidden = true
content = """
<p>
If you asked me four years ago why someone should use Rust,
chances are I would regurgitate some rough ideas about safety, race conditions, and/or performance.
So why use Rust today?
</p>

<h3>how it started</h3>

<p>

</p>
"""
