name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --bin dwbrite-com
      - uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: ~/
          host: "dwbrite.com"
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
