name: Container CI / Latest
on:
  push:
    branches: [ master ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install podman and podman-compose
      run: sudo apt-get -y install podman python3-pip && pip3 install podman-compose
    - name: Podman login
      # if container registry changes, be sure to change them in docker-compose.yml
      run: podman login docker.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build container images
      run: podman-compose build
    - name: Push images to registry
      run: podman-compose push
