name: CI
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: dwbrite.com
        username: ${{ secrets.USERNAME }}
        command_timeout: 15m
        key: ${{ secrets.KEY }}
        script: |
          cd /var/tmp & git clone git@github.com:dwbrite/website-rs
          cd /var/tmp/website-rs ; git pull ; cargo +nightly build --bin dwbrite-com --release

    - name: Copy files
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: dwbrite.com
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cp -r /var/tmp/website-rs/dwbrite-com /var/tmp/dwbrite.com
          cp -r /var/tmp/website-rs/target/release/dwbrite-com /var/tmp/dwbrite.com/target/dwbrite.com
