name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          command: |
            cd /var/tmp/website-rs
            git clone https://github.com/dwbrite/website-rs.git
            cargo +nightly build --bin --release dwbrite-com
            cp -r ./dwbrite-com /var/tmp/dwbrite.com
            cp -r ./target/release/dwbrite-com /var/tmp/dwbrite.com/target/dwbrite.com
          hosts: "${{ secrets.USERNAME }}@dwbrite.com"
          privateKey: ${{ secrets.KEY }}
