name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: dwbrite.com
        username: ${{ secrets.USERNAME }}
        command_timeout: 15m
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.KEY }}
        # I guess let's just forgo the clone for now :s
        script: |
          cd /var/tmp & git clone git@github.com:dwbrite/website-rs; cd website-rs ; git pull & \
          cargo +nightly build --bin dwbrite-com --release & \
          cp -r /var/tmp/website-rs/dwbrite-com /var/tmp/dwbrite.com & \
          cp -r /var/tmp/website-rs/target/release/dwbrite-com /var/tmp/dwbrite.com/target/dwbrite.com
          
